stages:
- unit_tests
- integration_tests

unit-tests:
  stage: unit_tests
  image: node:25
  script:
    - npm install
    - npm test
    - echo "Unit tests completed."
  artifacts:
    reports:
      junit: tmp/test-results.xml
    when: always
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)%/'